import ChecklistItem from "../ChecklistItem";
import { EntityStatus } from "../Enums";
import Location from "../Location";
import Type from "../Type";
import User from "../User";
import EntityAssign from "./EntityAssign";
import Breakdown from "./Breakdown";
import EntityHistory from "./EntityHistory";
import EntityPeriodicMaintenance from "./EntityPeriodicMaintenance";
import EntityRepairRequest from "./EntityRepairRequest";
import SparePR from "./SparePR";
import Repair from "./Repair";
import Division from "../Division";
import HullType from "../HullType";

export interface Entity {
  id: number;
  createdBy?: User;
  type?: Type;
  machineNumber?: string;
  registeredDate?: Date;
  model?: string;
  location?: Location;
  division?: Division;
  engine?: string;
  currentRunning?: number;
  lastService?: number;
  currentMileage?: number;
  lastServiceMileage?: number;
  interService?: number;
  measurement?: string;
  brand?: string;
  parentEntityId?: number;
  note?: string;
  hullType?: HullType;
  dimension?: number;
  registryNumber?: string;
  deletedAt?: Date;
  status: EntityStatus;
  statusChangedAt: Date;
  assignees: EntityAssign[];
  checklistItems: ChecklistItem[];
  periodicMaintenancePlans: EntityPeriodicMaintenance[];
  repairs: Repair[];
  breakdowns: Breakdown[];
  sparePRs: SparePR[];
  histories: EntityHistory[];
  subEntities?: Entity[] | undefined;
}
