import { FaGlobe } from "react-icons/fa";
import classes from "./Machine.module.css";

const Machine = (props:any) => {
  return (
    <div className={classes["machinaries-wrapper"]}>
      <div className={classes["machinaries-wrapper__user-details-container"]}>
        <div className={classes["machinaries-wrapper__user-details-wrapper"]}>
          <div
            className={
              classes["machinaries-wrapper__machinaries-details__info-wrapper"]
            }
          >
            <div
              className={
                classes[
                  "machinaries-wrapper__machinaries-details__priority-wrapper"
                ]
              }
            >
              <div
                className={
                  classes[
                    "machinaries-wrapper__machinaries-details__priority-title"
                  ]
                }
              >
                {props.machine.id}
              </div>
              <div
                className={
                  classes[
                    "machinaries-wrapper__machinaries-details__category-title"
                  ]
                }
              >
                Ex-31
              </div>
              <div
                className={
                  classes[
                    "machinaries-wrapper__machinaries-details__category-title"
                  ]
                }
              >
                {props.machine.zone} - {props.machine.location}
              </div>
              <div
                className={
                  classes[
                    "machinaries-wrapper__machinaries-details__category-title"
                  ]
                }
              >
                <FaGlobe /> Registered at <span>{props.machine.registeredDate}</span>
              </div>
            </div>
          </div>
        </div>
        <div className={classes["machinaries-wrapper__divider"]}></div>
        <div
          className={
            classes["machinaries-wrapper__machinaries-details-wrapper"]
          }
        >
          <div
            className={
              classes["machinaries-wrapper__machinaries-details__title"]
            }
          ></div>
          <div
            className={
              classes[
                "machinaries-wrapper__machinaries-details__info-container"
              ]
            }
          >
            <div
              className={
                classes[
                  "machinaries-wrapper__machinaries-details__info-wrapper"
                ]
              }
            >
              <div
                className={
                  classes[
                    "machinaries-wrapper__machinaries-details__category-wrapper"
                  ]
                }
              >
                <div
                  className={
                    classes[
                      "machinaries-wrapper__machinaries-details__category-title"
                    ]
                  }
                >
                  Model:{" "}
                  <span
                    className={
                      classes[
                        "machinaries-wrapper__machinaries-details__group-name"
                      ]
                    }
                  >
                    {props.machine.model}
                  </span>
                </div>
                <div
                  className={
                    classes[
                      "machinaries-wrapper__machinaries-details__category-title"
                    ]
                  }
                >
                  Type:{" "}
                  <span
                    className={
                      classes[
                        "machinaries-wrapper__machinaries-details__group-name"
                      ]
                    }
                  >
                    {props.machine.type}
                  </span>
                </div>
              </div>
              <div
                className={
                  classes[
                    "machinaries-wrapper__machinaries-details__priority-wrapper"
                  ]
                }
              >
                <div
                  className={
                    classes[
                      "machinaries-wrapper__machinaries-details__priority-title"
                    ]
                  }
                >
                  Current running (hr):{" "}
                  <span
                    className={
                      classes[
                        "machinaries-wrapper__machinaries-details__group-name"
                      ]
                    }
                  >
                    {props.machine.currentRunningHrs}
                  </span>
                </div>
                <div
                  className={
                    classes[
                      "machinaries-wrapper__machinaries-details__category-title"
                    ]
                  }
                >
                  Last service (hr):{" "}
                  <span
                    className={
                      classes[
                        "machinaries-wrapper__machinaries-details__group-name"
                      ]
                    }
                  >
                    3133
                  </span>
                </div>
                <div
                  className={
                    classes[
                      "machinaries-wrapper__machinaries-details__category-title"
                    ]
                  }
                >
                  Inter service (hr):{" "}
                  <span
                    className={
                      classes[
                        "machinaries-wrapper__machinaries-details__group-name"
                      ]
                    }
                  >
                    13
                  </span>
                </div>
              </div>
            </div>
            <div
              className={
                classes[
                  "machinaries-wrapper__machinaries-details__info-wrapper"
                ]
              }
            >
              <div
                className={
                  classes[
                    "machinaries-wrapper__machinaries-details__agent-wrapper"
                  ]
                }
              >
                <div
                  className={
                    classes[
                      "machinaries-wrapper__machinaries-details__agent-title"
                    ]
                  }
                >
                  Spare pr date:{" "}
                  <span
                    className={
                      classes[
                        "machinaries-wrapper__machinaries-details__group-name"
                      ]
                    }
                  >
                    12/2/2022
                  </span>
                </div>
                <div
                  className={
                    classes[
                      "machinaries-wrapper__machinaries-details__agent-title"
                    ]
                  }
                >
                  Spare pr status:{" "}
                  <span
                    className={
                      classes[
                        "machinaries-wrapper__machinaries-details__group-name"
                      ]
                    }
                  >
                    Status
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div
          className={
            classes["machinaries-wrapper__machinaries-activity-wrapper"]
          }
        >
          <div
            className={
              classes[
                "machinaries-wrapper__machinaries-activity__started-wrapper"
              ]
            }
          >
            <div
              className={
                classes["machinaries-wrapper__machinaries-activity__started"]
              }
            >
              Estimated Completion:
              <span
                className={
                  classes[
                    "machinaries-wrapper__machinaries-activity__started-date"
                  ]
                }
              >
                11/11/2021
              </span>
            </div>
            <div
              className={
                classes["machinaries-wrapper__machinaries-activity__status"]
              }
            >
              Working
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Machine;
